### ISSUE TITLE
Confirmation Dialog on "Load Keyboard" if there are unsaved changes

### ISSUE THREAD

**Issue by ShikenNuggets** [ThoNohT/NohBoard#112] opened 2020-01-09 04:55 UTC
In NohBoard Rewrite 1.2.2, I just spent somewhere around an hour working on a layout. Towards the end of that, I accidentally clicked on "load keyboard", which caused NohBoard to _immediately discard all of my changes without warning_. Granted, I definitely should have been saving throughout, but nonetheless that's a pretty horrendous user experience to just instantly throw away unsaved changes when that is _almost certainly not_ what the user intended.

There definitely needs to be some sort of confirmation dialog on the "load keyboard" action if there are any unsaved changes to prevent situations like this, and I imagine there are several other places where this confirmation dialog should be used as well, such as on exiting the program.

**Comment by joao7yt** [comment] 2020-01-09 04:57
agree

**Comment by ThoNohT** [comment] 2020-04-03 15:15
This should be solved in 89d58d88e28be79dd45ca8196ad754a1cd137445. Man, that was a lot more complicated to get right than I thought it would.

Could anyone please check whether this works properly?

**Comment by joao7yt** [comment] 2020-04-04 03:43
Tested, working fine.

**Comment by ThoNohT** [comment] 2020-04-04 11:41
I actually did a full rewrite of undo/redo and change tracking because I wasn't really happy about how it worked now. And I think I fixed some hidden bus even. This is done in 525725e2ae6409586e323d15cc3896ffc0689701.

I guess some more testing might be wise: https://ci.appveyor.com/project/ThoNohT/nohboard/builds/31950268/artifacts

**Comment by joao7yt** [comment] 2020-04-04 15:21
Crashing when messing with undo...

How to reproduce: load a joao7yt layout selecting the first style. Start editing. Select any element. Press ctrl+z. Select any element again.

Log attached.
[20200404-122104.24717101.log](https://github.com/ThoNohT/NohBoard/files/4431792/20200404-122104.24717101.log)

**Comment by ThoNohT** [comment] 2020-04-04 15:24
Alright, I'll see if I can figure this out.

**Comment by ThoNohT** [comment] 2020-04-04 15:32
e2730b394878b6193d988e1617ade26801ee23c0 Should fix it.

https://ci.appveyor.com/project/ThoNohT/nohboard/builds/31952864/artifacts

**Comment by joao7yt** [comment] 2020-04-04 15:36
Seems to be consistent now.

**Comment by ThoNohT** [comment] 2020-04-04 15:37
It now also asks when closing NohBoard BTW. I just sneaked that in.
But I think that's enough to close this issue now.

**Closed by ThoNohT** 2020-04-04 15:37 UTC
Labels: Feature Request, Testing
