### ISSUE TITLE
Nohboard disappears, unable to alt-tab or open the window.

### ISSUE THREAD

**Issue by jackfranzen** [ThoNohT/NohBoard#58] opened 2018-04-11 08:03 UTC
After a bit of use, i'm unable to alt-tab into nohboard. I can see it running in the list of programs in the alt-tab menu, and on the taskbar, but i can't get it to open.

It wouldn't be a problem, but if I'm unable to open nohboard I can't click it to change the style. This has happened on two pcs now. (win 10,  OBS, epic games, discord, and synapse running) Both PCs used one 144hz monitor (1080p) and one 60hz monitor (2560x1440)

It doesn't seem to happen when I start my pc, but after a while there's nothing i can do to get it back. If this issue hasn't been reported, I'm betting it's my monitor situtation.

**Comment by ThoNohT** [comment] 2018-04-11 10:28
This is most likely a duplicate of #50 Could you try the workaround there to and confirm that it is?

**Comment by joao7yt** [comment] 2018-04-12 01:06
Yeah, i bet you have closed nohboard while it was minimized...

**Comment by jackfranzen** [comment] 2018-04-12 08:26
it was a duplicate, sorry missed that. The workaround works

**Closed** 2018-09-22 13:57 UTC
Labels: Duplicate
