### ISSUE TITLE
Support for joy/arcade sticks?

### ISSUE THREAD

**Issue by lvangh** [ThoNohT/NohBoard#105] opened 2019-08-13 05:35 UTC
Any chance Noh will support other input devices like fightsticks? 
![image](https://user-images.githubusercontent.com/19690096/62917535-7980de00-bd51-11e9-9cf5-be3f1c105234.png)

**Comment by ThoNohT** [comment] 2020-02-18 07:36
Duplicate of #22.

**Closed by ThoNohT** 2020-02-18 07:36 UTC
