### ISSUE TITLE
Can't set both OutlineWidth to 2

### ISSUE THREAD

**Issue by JapanYoshi** [ThoNohT/NohBoard#108] opened 2019-09-27 01:42 UTC
I tried to set OutlineWidth of both idle and pressed keys to 2, but every time I saved it from the GUI, it turned one of them to 1. I had to manually edit default.style in order to change it.

**Comment by ThoNohT** [comment] 2020-04-03 15:20
I'm unable to reproduce this. I  tried it both in the keyboard style, and in a key's element style. In both cases I was able to successfully edit the outline width of either or both at the same time.

**Comment by ThoNohT** [comment] 2020-04-04 17:59
Actually managed to reproduce something like this. Probably related. Good news is it'll be fixed in the next commit.

**Comment by ThoNohT** [comment] 2020-04-04 18:05
Fixed in 4d0ea4d169a5e36bb081dcc3f5429fc13ed90786

**Closed by ThoNohT** 2020-04-04 18:05 UTC
Labels: Bug
